-- SQLite
CREATE TABLE Books(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(200),
    Author INT REFERENCES Authors(ID));

CREATE TABLE Authors(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(200));

CREATE TABLE Customers(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(200),
    Email VARCHAR(254));

CREATE TABLE Rents(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BookID INT REFERENCES Books(ID),
    CustomerID INT REFERENCES Customers(ID),
    State VARCHAR(30));





